### PR TITLE
Better testing of roles changes

### PR DESCRIPTION
**Pull request by cole-miller**
WIP -- details to come.

### CODE REVIEW

**Comment by cole-miller** [comment]
I've been trying without success to figure out why CI fails -- it seems we get a connection failure in the `ready` function in `client.clj` before the test binary is even invoked, and I can't see how the changes in this PR affect Jepsen startup.

**Comment by MathieuBordere** [comment]
I also don't see an obvious error, you'll probably have to split the commits and check where it starts to fail.

**Comment by cole-miller** [comment]
Still probably need to squash a number of bugs, but I've settled on a approach that I'm happy with, which I'll describe here.

We want to check that if we perturb the cluster, then heal it, the role management code in go-dqlite/app successfully converges the cluster roles to a *stable* state where no adjustments are required. That means that we have the desired number of voters and standbys and that these are distributed across failure domains in a suitable way.

So: we add a new endpoint to the toy server code (resources/app.go) that dry-runs the role management algorithm and triggers our Jepsen assertion checker if adjustments are needed. Then we update the "main loop" for our Jepsen tests to (Sometimes) heal the cluster and then hit this endpoint after each run of a nemesis package.

Implementation-wise, we have a `:stable` operation that's generated directly by the "main loop" and handled by a sort of dummy nemesis. This nemesis doesn't generate any operations itself, just sends a request to our new endpoint when it sees the `:stable` op.

**Comment by cole-miller** [comment]
I don't think the assertion checker is doing its job -- I added `start-stop-daemon:` to the regex it uses to look for problems in the log file and it doesn't seem to be picking up when #33 happens, although I see that error message in the uploaded app.log.

**Comment by cole-miller** [comment]
Ah, so the problem was that we were getting an error from nsenter before actually running the egrep command, and then that exception was getting swallowed by a try/catch, which caused the assertion checker to think everything was fine.

As for nsenter, I think the problem is that we're trying to enter a namespace that we designate by the PID of a process that's already exited. The solution is probably to create the namespaces directly so we we can refer to them by name later even after the original process is done.

**Comment by cole-miller** [comment]
> The solution is probably to create the namespaces directly so we we can refer to them by name later even after the original process is done.

Thinking out loud some more... the lifetime of the namespaces is actually tied to that of the `unshare sleep inf` that's spawned by the setup code in containers.clj. I think we just need to plumb that PID down to the functions in control.clj somehow.

**Comment by cole-miller** [comment]
It looks like with the current branch, all the test failures are either https://github.com/canonical/raft/issues/314 or "cluster not yet stable" (the check we're introducing here). Next is looking at whether that new check is too sensitive.

**Comment by MathieuBordere** [comment]
lgtm!

**Pull request merged**
